added exit code to python

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -27,4 +27,9 @@ jobs:
         working-directory: tests # Set working directory to 'tests'
         run: |
           python3 general_tests.py
+           exit_code=$? # Get the exit code of the previous command
+           if [ $exit_code -ne 0 ]; then
+            echo "❌ Tests failed. Exiting with status code $exit_code."
+            exit $exit_code # Exit the job with the same status code as the Python script
+           fi
       - run: echo "🍏 This job's status is ${{ job.status }}."
