refactor(tests) comment router tests

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -63,14 +63,14 @@ jobs:
             echo "❌ Tests failed. Exiting with status code $exit_code."
             exit $exit_code
            fi
-      - name: Run C++ router tests
-        if: always()
-        working-directory: tests # Set working directory to 'tests'
-        run: |
-          c++ router.cpp -o parse && ./parse
-           exit_code=$?
-           if [ $exit_code -ne 0 ]; then
-            echo "❌ Tests failed. Exiting with status code $exit_code."
-            exit $exit_code
-           fi
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+      # - name: Run C++ router tests
+      #   if: always()
+      #   working-directory: tests # Set working directory to 'tests'
+      #   run: |
+      #     c++ router.cpp -o parse && ./parse
+      #      exit_code=$?
+      #      if [ $exit_code -ne 0 ]; then
+      #       echo "❌ Tests failed. Exiting with status code $exit_code."
+      #       exit $exit_code
+      #      fi
+      # - run: echo "🍏 This job's status is ${{ job.status }}."
