feat(tests): add tests

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -72,6 +72,16 @@ jobs:
             echo "❌ Tests failed. Exiting with status code $exit_code."
             exit $exit_code
            fi
+      - name: Run Error codes tests
+        if: always()
+        working-directory: tests # Set working directory to 'tests'
+        run: |
+          ./error_codes_test.sh
+           exit_code=$?
+           if [ $exit_code -ne 0 ]; then
+            echo "❌ Tests failed. Exiting with status code $exit_code."
+            exit $exit_code
+           fi
       - name: Run C++ parser tests
         if: always()
         working-directory: tests # Set working directory to 'tests'
