added c++ tests

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,5 +1,5 @@
 name: GitHub Actions Demo
-run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
+run-name: ${{ github.actor }} is testing ${{ github.repository }}
 on:
   push: # Trigger on push events
   pull_request: # Trigger on pull request events
@@ -24,6 +24,7 @@ jobs:
       - name: Start webserv in background
         run: ./webserv &
       - name: Run Config file tests
+        if: always()
         working-directory: tests/config
         run: |
           ./config_test.sh
@@ -40,6 +41,16 @@ jobs:
         working-directory: tests # Set working directory to 'tests'
         run: |
           python3 general_tests.py
+           exit_code=$?
+           if [ $exit_code -ne 0 ]; then
+            echo "❌ Tests failed. Exiting with status code $exit_code."
+            exit $exit_code
+           fi
+      - name: Run C++ parser tests
+        if: always()
+        working-directory: tests # Set working directory to 'tests'
+        run: |
+          c++ parser.cpp -o parse && ./parse
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
             echo "❌ Tests failed. Exiting with status code $exit_code."
