fix: fix alignment

diff --git a/.github/workflows/webserv.yml b/.github/workflows/webserv.yml
--- a/.github/workflows/webserv.yml
+++ b/.github/workflows/webserv.yml
@@ -107,14 +107,15 @@ jobs:
       - name: Make parallel_cgi/duration_ts.sh executable
         run: chmod +x tests/parallel_cgi/duration_ts.sh
       - name: Run parallel CGIs Test
-        run: ./tests/parallel_cgi/duration_ts.sh
-          exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-          echo "❌ Parallel CGI tests failed. Exiting with status code $exit_code."
-          exit $exit_code
-          else
-          echo "✅ Parallel CGI tests passed."
-          fi
+        run: |
+          ./tests/parallel_cgi/duration_ts.sh
+            exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              echo "❌ Parallel CGI tests failed. Exiting with status code $exit_code."
+              exit $exit_code
+            else
+              echo "✅ Parallel CGI tests passed."
+            fi
       - name: Check for Zombie Processes
         run: |
           zombies=$(ps aux | grep 'Z' | grep -v grep)
