test(yaml github actions): fix syntax

diff --git a/.github/workflows/webserv.yml b/.github/workflows/webserv.yml
--- a/.github/workflows/webserv.yml
+++ b/.github/workflows/webserv.yml
@@ -110,10 +110,10 @@ jobs:
         run: ./tests/parallel_cgi/durations_ts.sh
           exit_code=$?
           if [ $exit_code -ne 0 ]; then
-             echo "❌ Parallel CGI tests failed. Exiting with status code $exit_code."
-             exit $exit_code
+          echo "❌ Parallel CGI tests failed. Exiting with status code $exit_code."
+          exit $exit_code
           else
-            echo "✅ Parallel CGI tests passed."
+          echo "✅ Parallel CGI tests passed."
           fi
       - name: Check for Zombie Processes
         run: |
@@ -124,7 +124,7 @@ jobs:
             exit 1
           else
             echo "No zombie processes found."
-     - name: Check for open listening sockets
+      - name: Check for open listening sockets
         run: |
           listening_sockets=$(lsof -iTCP -sTCP:LISTEN -nP | grep 'webserv')
           if [ -z "$listening_sockets" ]; then
@@ -135,18 +135,18 @@ jobs:
             echo "$listening_sockets"
           fi
 
-    - name: Stop webserv
-      run: pkill -f webserv
+      - name: Stop webserv
+        run: pkill -f webserv
 
-    - name: Verify no lingering sockets
-      run: |
-        sleep 5  # Give some time for sockets to close properly
-        lingering_sockets=$(lsof -iTCP -sTCP:LISTEN -nP | grep 'webserv')
-        if [ -n "$lingering_sockets" ]; then
-          echo "Unexpected lingering sockets found:"
-          echo "$lingering_sockets"
-          exit 1
-        else
-          echo "No lingering sockets found."
+      - name: Verify no lingering sockets
+        run: |
+          sleep 5  # Give some time for sockets to close properly
+          lingering_sockets=$(lsof -iTCP -sTCP:LISTEN -nP | grep 'webserv')
+          if [ -n "$lingering_sockets" ]; then
+            echo "Unexpected lingering sockets found:"
+            echo "$lingering_sockets"
+            exit 1
+          else
+            echo "No lingering sockets found."
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
